"""FFmpeg finalizer container configuration constants."""

STEP_NAME = "ffmpeg-finalizer"

VERTICAL_WIDTH = 1080
VERTICAL_HEIGHT = 1920

VERTICAL_WIDTH_ENV = "VERTICAL_WIDTH"
VERTICAL_HEIGHT_ENV = "VERTICAL_HEIGHT"
CROP_STRATEGY_ENV = "CROP_STRATEGY"
CROP_STRATEGY = "center"

H264_CRF = 20
H264_PRESET = "medium"
H264_PROFILE = "high"
AUDIO_BITRATE = "128k"
AUDIO_SAMPLE_RATE = 44100
LOUDNORM_TARGET = "-14"
LOUDNORM_TP = "-1"
LOUDNORM_LRA = "11"